#!/usr/bin/env node

// Matches YouTube video titles to GymMate exercise names
// Input:  scripts/youtube-videos.json (from scraper or manual entry)
// Output: src/data/exercise-videos.js (importable mapping)

const fs = require('fs');
const path = require('path');

// Import exercise list
const exercisesPath = path.join(__dirname, '../src/data/exercises.js');
const exercisesCode = fs.readFileSync(exercisesPath, 'utf8');
const exerciseNamesMatch = exercisesCode.match(/name: '([^']+)'/g);
if (!exerciseNamesMatch) {
  console.error('Could not parse exercise names from exercises.js');
  process.exit(1);
}
const exerciseNames = exerciseNamesMatch.map(m => m.match(/name: '([^']+)'/)[1]);

// Load scraped videos
const videosPath = path.join(__dirname, 'youtube-videos.json');
if (!fs.existsSync(videosPath)) {
  console.error(`${videosPath} not found. Run scrape-youtube-shorts.js first or create it manually.`);
  process.exit(1);
}
const videos = JSON.parse(fs.readFileSync(videosPath, 'utf8'));

console.log(`Loaded ${exerciseNames.length} exercises, ${videos.length} videos`);

// Fuzzy match helper
function normalize(str) {
  return str.toLowerCase()
    .replace(/[()]/g, '')
    .replace(/[-–—]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function matchScore(exerciseName, videoTitle) {
  const exNorm = normalize(exerciseName);
  const vidNorm = normalize(videoTitle);

  // Exact match
  if (exNorm === vidNorm) return 100;

  // Video title contains full exercise name
  if (vidNorm.includes(exNorm)) return 90;

  // Exercise name contains full video title (rare but possible)
  if (exNorm.includes(vidNorm)) return 85;

  // Word overlap score
  const exWords = exNorm.split(' ');
  const vidWords = vidNorm.split(' ');
  const overlap = exWords.filter(w => w.length > 2 && vidWords.includes(w)).length;
  if (overlap === 0) return 0;

  return Math.min(80, overlap * 20);
}

// Match each video to best exercise
const matches = [];
const unmatchedVideos = [];

for (const video of videos) {
  let bestMatch = null;
  let bestScore = 0;

  for (const exerciseName of exerciseNames) {
    const score = matchScore(exerciseName, video.title);
    if (score > bestScore) {
      bestScore = score;
      bestMatch = exerciseName;
    }
  }

  if (bestScore >= 60) {
    matches.push({
      exerciseName: bestMatch,
      videoTitle: video.title,
      videoId: video.videoId,
      url: video.url,
      confidence: bestScore
    });
  } else {
    unmatchedVideos.push({ title: video.title, bestGuess: bestMatch, score: bestScore });
  }
}

// Output results
console.log(`\n✅ Matched ${matches.length} videos:`);
matches.forEach(m => {
  console.log(`   ${m.confidence}% — ${m.exerciseName} ← ${m.videoTitle}`);
});

if (unmatchedVideos.length > 0) {
  console.log(`\n⚠️  ${unmatchedVideos.length} videos with low confidence (<60%):`);
  unmatchedVideos.forEach(v => {
    console.log(`   ${v.score}% — ${v.title} → ${v.bestGuess}`);
  });
}

// Generate TypeScript/JS mapping file
const outputPath = path.join(__dirname, '../src/data/exercise-videos.js');
const code = `// Auto-generated by scripts/match-videos.js
// YouTube Shorts from @atppersonaltraining4506 matched to GymMate exercises

export const EXERCISE_VIDEOS = {
${matches.map(m => `  '${m.exerciseName}': { videoId: '${m.videoId}', url: '${m.url}' },`).join('\n')}
};

// Get video for an exercise by name
export function getExerciseVideo(exerciseName) {
  return EXERCISE_VIDEOS[exerciseName] || null;
}
`;

fs.writeFileSync(outputPath, code);
console.log(`\n📦 Generated ${outputPath}`);
console.log(`   Ready to import in ExerciseDetailScreen.js`);
